### ISSUE TITLE
一个BUG. 

### ISSUE THREAD

**Issue by geekqian** [HMY314/DropPopMenu#2]
添加了3个item, 文字最长的放在第一个的时候, 正常显示文字.
放在第二个的时候, 被截掉了一段.
查阅源码, 发现最大宽度有判断根据最大文字来设置. 但是没有效果, 暂时还在找这个BUG的位置

**Comment by HMY314** [comment]
问题已解决，将item_drop_pop_menu.xml中TextView的android:singleLine="true"改为 android:maxLines="1" 即可解决

**Comment by geekqian** [comment]
@HMY314 测试了下, 之前是显示不下时为省略号, 现在是直接截断不加省略号.
